apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service-deployment
spec:
  selector:
    matchLabels:
      app: config-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service-deployment
    spec:
      containers:
        - name: config-server
          image: yuyunisse/config-server
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    app: config-server-service
spec:
  selector:
    app: config-service-deployment
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer