apiVersion: apps/v1
kind: Deployment
metadata:
  name: historial-service-deployment
  labels:
    app: historial-service-deployment
spec:
  selector:
    matchLabels:
      app: historial-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: historial-service-deployment
    spec:
      containers:
        - name: historial-service
          image: yuyunisse/historial-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_HIS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_HIS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_HIS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_HIS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_HIS