-- Conectar a la base de datos postgres
\c postgres

-- Crear la nueva base de datos
CREATE DATABASE "historial-db";

--Conectar a la nueva base de dato
\c "historial-db";
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bono; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bono (
    fecha date,
    id integer NOT NULL,
    patente character varying(255)
);


ALTER TABLE public.bono OWNER TO postgres;

--
-- Name: bono_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bono ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bono_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: convenio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.convenio (
    anio integer,
    cantidad integer,
    id integer NOT NULL,
    mes integer,
    monto integer,
    marca character varying(255)
);


ALTER TABLE public.convenio OWNER TO postgres;

--
-- Name: convenio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.convenio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.convenio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle (
    id integer NOT NULL,
    fechai date,
    horai time(6) without time zone,
    monto double precision,
    patente character varying(255),
    reparacion character varying(255)
);


ALTER TABLE public.detalle OWNER TO postgres;

--
-- Name: detalle_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_entity (
    fechai date,
    horai time(6) without time zone,
    id integer NOT NULL,
    monto double precision,
    patente character varying(255),
    reparacion character varying(255)
);


ALTER TABLE public.detalle_entity OWNER TO postgres;

--
-- Name: detalle_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historial (
    id integer NOT NULL,
    descuentos double precision,
    fechad date,
    fechai date,
    fechas date,
    horad time(6) without time zone,
    horai time(6) without time zone,
    horas time(6) without time zone,
    iva double precision,
    patente character varying(255),
    recargos double precision,
    total double precision,
    totalr double precision
);


ALTER TABLE public.historial OWNER TO postgres;

--
-- Name: historial_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historial_entity (
    descuentos double precision,
    fechad date,
    fechai date,
    fechas date,
    horad time(6) without time zone,
    horai time(6) without time zone,
    horas time(6) without time zone,
    id integer NOT NULL,
    iva double precision,
    recargos double precision,
    total double precision,
    totalr double precision,
    patente character varying(255)
);


ALTER TABLE public.historial_entity OWNER TO postgres;

--
-- Name: historial_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historial_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bono; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bono (fecha, id, patente) FROM stdin;
2024-06-01	7	sklamlsm11
\.


--
-- Data for Name: convenio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.convenio (anio, cantidad, id, mes, monto, marca) FROM stdin;
3343	3	1	12	7676	7ksscscs
83759	342	2	5	453	FORD
9342	2	3	3	3	Toyota
2024	1	4	6	60000	Toyota
\.


--
-- Data for Name: detalle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle (id, fechai, horai, monto, patente, reparacion) FROM stdin;
1	2024-02-02	14:30:00	70000	dknsv	nvlsnv
2	2023-06-27	14:30:00	7676	sndsvlsn	3343
3	0005-03-04	02:34:00	4384944	sndsvlsn	dkrfregr
4	2023-06-27	14:30:00	7676	sndsvlsn	3343
5	2023-06-27	14:30:00	7676	sndsvlsn	3343
6	2023-06-27	14:30:00	7676	sndsvlsn	33kdnvsl
7	2023-06-27	14:30:00	7676	sndsvlsn	33kdnvsl
8	2023-06-27	14:30:00	7676	sndsvlsn	33kkjkkmksl
9	2023-06-27	14:30:00	0	sndsvlsn	33kkksl
10	2023-06-03	00:59:00	0	sndsvlsn	Reparación del Sistema de Aire Acondicionado y Calefacción
11	2022-04-07	15:07:00	130000	djcksjdj	 Servicio del Sistema de Refrigeración
13	2022-04-07	14:01:00	100000	djcksjdj	Reparación de Neumáticos y Ruedas
14	2024-06-01	12:02:00	80000	sklamlsm11	Reparación y Reemplazo del Parabrisas y Cristales
15	2024-06-01	00:04:00	0	sklamlsm11	Reparaciones del Sistema de Escape
16	2024-06-01	12:06:00	180000	sklamlsm11	Reparación del Sistema de Aire Acondicionado y Calefacción
12	2022-04-07	01:59:00	130000	djcksjdj	Servicio del Sistema de Refrigeración
17	2024-06-01	14:03:00	800000	sklamlsm11	Reparaciones del Motor
18	2024-02-05	14:01:00	119999	njsnljd12	Reparaciones del Sistema de Frenos
19	2024-05-02	16:01:00	130000	njsnljd12	Reparaciones del Sistema de Combustible
\.


--
-- Data for Name: detalle_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_entity (fechai, horai, id, monto, patente, reparacion) FROM stdin;
\.


--
-- Data for Name: historial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historial (id, descuentos, fechad, fechai, fechas, horad, horai, horas, iva, patente, recargos, total, totalr) FROM stdin;
4	\N	\N	2023-06-27	\N	\N	13:49:52.78	\N	\N	sndsvlsn	\N	\N	\N
5	\N	\N	2023-06-03	\N	\N	19:56:42.19	\N	\N	sndsvlsn	\N	\N	\N
6	0	2024-06-29	2022-04-07	2023-06-30	01:32:29.234	20:06:50.465	14:30:00	68400	djcksjdj	6696000	7124400	360000
8	\N	\N	2024-02-05	\N	\N	19:50:15.738	\N	\N	njsnljd12	\N	\N	\N
9	6500	2024-07-07	2024-05-02	2024-05-15	19:56:24.008	19:54:50.842	15:02:00	24700	njsnljd12	344500.00000000006	492700.00000000006	130000
7	0	2024-07-09	2024-06-01	2024-06-15	01:26:57.618	18:45:50.93	14:01:00	201400	sklamlsm11	1696000.0000000002	2957400	1060000
\.


--
-- Data for Name: historial_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historial_entity (descuentos, fechad, fechai, fechas, horad, horai, horas, id, iva, recargos, total, totalr, patente) FROM stdin;
\.


--
-- Name: bono_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bono_id_seq', 8, true);


--
-- Name: convenio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.convenio_id_seq', 4, true);


--
-- Name: detalle_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_entity_id_seq', 1, false);


--
-- Name: detalle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_id_seq', 19, true);


--
-- Name: historial_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historial_entity_id_seq', 1, false);


--
-- Name: historial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historial_id_seq', 9, true);


--
-- Name: bono bono_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bono
    ADD CONSTRAINT bono_pkey PRIMARY KEY (id);


--
-- Name: convenio convenio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.convenio
    ADD CONSTRAINT convenio_pkey PRIMARY KEY (id);


--
-- Name: detalle_entity detalle_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_entity
    ADD CONSTRAINT detalle_entity_pkey PRIMARY KEY (id);


--
-- Name: detalle detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle
    ADD CONSTRAINT detalle_pkey PRIMARY KEY (id);


--
-- Name: historial_entity historial_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial_entity
    ADD CONSTRAINT historial_entity_pkey PRIMARY KEY (id);


--
-- Name: historial historial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial
    ADD CONSTRAINT historial_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

