apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_VEH: vehiculo-db-service
  DB_DBNAME_VEH: vehiculo-db
  DB_PORT_VEH: "5432"
  DB_HOST_HIS: historial-db-service
  DB_DBNAME_HIS: historial-db
  DB_PORT_HIS: "5433"
  DB_HOST_REP: reparaciones-db-service
  DB_DBNAME_REP: reparaciones-db
  DB_PORT_REP: "5434"
  