apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparaciones-service-deployment
  labels:
    app: reparaciones-service-deployment
spec:
  selector:
    matchLabels:
      app: reparaciones-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reparaciones-service-deployment
    spec:
      containers:
        - name: reparaciones-service
          image: yuyunisse/reparaciones-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REP
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REP
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REP
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REP
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REP