apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-service-deployment
  labels:
    app: reportes-service-deployment
spec:
  selector:
    matchLabels:
      app: reportes-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reportes-service-deployment
    spec:
      containers:
        - name: reportes-service
          image: yuyunisse/reportes-service
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"
          