-- Conectar a la base de datos postgres
\c postgres;

-- Crear la nueva base de datos
CREATE DATABASE "vehiculo-db";

-- Conectar a la nueva base de datos
\c "vehiculo-db";
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: vehiculo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehiculo (
    id integer NOT NULL,
    ano_fab integer,
    asientos integer,
    kilometraje double precision,
    marca character varying(255),
    modelo character varying(255),
    motor character varying(255),
    patente character varying(255),
    tipo character varying(255)
);


ALTER TABLE public.vehiculo OWNER TO postgres;

--
-- Name: vehiculo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehiculo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehiculo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: vehiculo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehiculo (id, ano_fab, asientos, kilometraje, marca, modelo, motor, patente, tipo) FROM stdin;
1	2019	4	1000	toyota	dfgdgd	gasolina	asdd44	suv
2	7676	2	453453	nvlsnv	777	70000	dkrfregrjnkjnk	999
3	30952	3	483	dnsvln	m,dvs	kdlsk	sndsvlsn	Hatchback
4	2020	4	328648	jkbckjsdkz	jxkbadbj	GASOLINA	djcksjdj	Hatchback
5	2021	4	3432	sncakndcsk	dncslncskl	GASOLINA	ndjsn	SUV
6	2024	2	181723	Toyota	kdmsk	ELECTRICO	sklamlsm11	Pickup
7	2021	4	183828	Honda	sdcsdc	GASOLINA	njsnljd12	Sedan
\.


--
-- Name: vehiculo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehiculo_id_seq', 7, true);


--
-- Name: vehiculo vehiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehiculo
    ADD CONSTRAINT vehiculo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

